### Test: Register a new provider (simulate GET /register)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwcm92aWRlcjEiLCJleHAiOjE3NTUxMDM3MTh9.U5ySUeTmgNTr7Zeo_reHcK8fBOULdt6rd2HJ_VjFQTc

GET http://localhost:8001/register
Accept: application/json
Authorization: Bearer {{token}}

###

GET http://146.148.40.168:8001/register
Accept: application/json
Authorization: Bearer {{token}}


###

### Test: Trigger endpoint (simulate GET /trigger)
GET http://localhost:8001/trigger
Accept: application/json


### Test: Trigger endpoint (simulate GET /trigger)
GET http://146.148.40.168:8001/trigger
Accept: application/json
Authorization: Bearer {{token}}

### Test: Data Service - Get all providers
GET http://localhost:8002/providers/
Accept: application/json

###

### Test: Data Service - Get provider by user_id
GET http://localhost:8002/providers/admin
Accept: application/json

###
