### Register a provider
POST http://localhost:8002/users/register
Content-Type: application/json

{
  "username": "provider1",
  "password": "testpassword",
  "type": "provider"
}

### Register a submitter
POST http://localhost:8002/users/register
Content-Type: application/json

{
  "username": "submitter1",
  "password": "testpassword",
  "type": "submitter"
}

### Fetch provider user
GET http://localhost:8002/users/provider1

### Fetch submitter user
GET http://localhost:8002/users/submitter1
